const blogs = [
  {
    type_of: 'article',
    id: 743441,
    title: "Let's come.... no, not Steph or the food.",
    description:
      'Have you ever gone to a interview and interviewer ask you a question. "Do you know what currying is...',
    readable_publish_date: "Jun 30 '24",
    slug: 'let-s-talk-about-curry-no-not-steph-or-the-food-4k1e',
    path: '/klawingco/let-s-talk-about-curry-no-not-steph-or-the-food-4k1e',
    url: 'https://dev.to/klawingco/let-s-talk-about-curry-no-not-steph-or-the-food-4k1e',
    comments_count: 0,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: '2024-06-30T08:01:03Z',
    positive_reactions_count: 5,
    cover_image: null,
    social_image: 'https://dev.to/social_previews/article/743441.png',
    canonical_url:
      'https://dev.to/klawingco/let-s-talk-about-curry-no-not-steph-or-the-food-4k1e',
    created_at: '2021-06-30T03:24:50Z',
    edited_at: null,
    crossposted_at: null,
    published_at: '2021-06-30T08:01:03Z',
    last_comment_at: '2021-06-30T08:01:03Z',
    reading_time_minutes: 5,
    tag_list: ['javascript', 'programming'],
    tags: 'javascript, programming',
    user: {
      name: 'Okello',
      username: 'klawingco',
      twitter_username: null,
      github_username: 'klawingco',
      user_id: 620099,
      website_url: 'https://kllawingco.com/',
      profile_image:
        'https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F620099%2F932387ee-a9ed-4ae0-a080-0927ed0ace1b.jpg',
      profile_image_90:
        'https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F620099%2F932387ee-a9ed-4ae0-a080-0927ed0ace1b.jpg',
    },
  },
  {
    type_of: 'article',
    id: 740101,
    title: 'Playing with Dependency injection in a Console app?',
    description:
      'A few days ago I was asked to create some console app that lets you ask some question around weather....',
    readable_publish_date: "Jun 26 '21",
    slug: 'playing-with-dependency-injection-in-a-console-app-3a4',
    path: '/klawingco/playing-with-dependency-injection-in-a-console-app-3a4',
    url: 'https://dev.to/klawingco/playing-with-dependency-injection-in-a-console-app-3a4',
    comments_count: 0,
    public_reactions_count: 5,
    collection_id: null,
    published_timestamp: '2021-06-26T13:43:54Z',
    positive_reactions_count: 5,
    cover_image: null,
    social_image: 'https://dev.to/social_previews/article/740101.png',
    canonical_url:
      'https://dev.to/klawingco/playing-with-dependency-injection-in-a-console-app-3a4',
    created_at: '2021-06-26T13:43:54Z',
    edited_at: '2021-06-27T03:51:40Z',
    crossposted_at: null,
    published_at: '2021-06-26T13:43:54Z',
    last_comment_at: '2021-06-26T13:43:54Z',
    reading_time_minutes: 4,
    tag_list: ['csharp', 'programming'],
    tags: 'csharp, programming',
    user: {
      name: 'Marc Lawingco',
      username: 'klawingco',
      twitter_username: null,
      github_username: 'klawingco',
      user_id: 620099,
      website_url: 'https://kllawingco.com/',
      profile_image:
        'https://media.dev.to/cdn-cgi/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F620099%2F932387ee-a9ed-4ae0-a080-0927ed0ace1b.jpg',
      profile_image_90:
        'https://media.dev.to/cdn-cgi/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F620099%2F932387ee-a9ed-4ae0-a080-0927ed0ace1b.jpg',
    },
  },
]
export default blogs
